name: 'MiniWebApp'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  intl: ^0.12.0
  args: any
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  di: ^3.3.0

  dart_to_js_script_rewriter: ^0.1.0

  js: ^0.6.0

transformers:
  - di
  - dart_to_js_script_rewriter
